# Web Server configuration
# Trigger restart comment 3
server.port=8082

# ActiveMQ Artemis configuration
spring.artemis.mode=embedded
spring.artemis.embedded.port=61616
spring.artemis.embedded.tcp-enabled=true

# Logging configuration
logging.level.org.apache.activemq.artemis=INFO
logging.level.org.springframework.jms=INFO
logging.level.com.ems.jmsservice=DEBUG

# Enable Jackson pretty printing
spring.jackson.serialization.indent_output=true

# H2 Datasource Properties
spring.datasource.url=jdbc:h2:file:./data/emsdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console Properties
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false
